# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@0.2.1
jobs:
 convert-Task:
    executor: python/default
    steps:
    - checkout
    - restore_cache:
      key: dependencies
    - python/install-deps
    - save_cache:
      key: dependencies
      path:
      - "venv"
    - run: echo 'export PATH=/home/circleci/.local/lib/python3.8/site-packages:$PATH' >> $BASH_ENV
    - run:
      name: Jupyter get HTML
      command:  jupyter nbconvert -execute -to html T1.ipynb
    - store_artifact:
      path: ./T1.html

workflows:
 main:
    jobs: 
      - convert-T1